FROM node:lts-alpine as build

WORKDIR /app

COPY package.json yarn.lock ./

RUN NODE_ENV=development yarn install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false

COPY . ./

ENV NODE_ENV=development

RUN yarn build:stg

FROM nginx:stable-alpine as base

COPY --from=build /app/dist /usr/share/nginx/html

COPY --from=build app/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]